project:
  type: website

website:
  title: "darklight"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    code-link: true
    highlight-style:
      light: arrow
      dark: arrow-dark
    theme:
      light: [cosmo, light.scss, custom.scss]
      dark: [cosmo, dark.scss, custom.scss]


editor: visual

